export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'
export const USER_FETCH_RESET = 'USER_FETCH_RESET'

export const USER_APPROVE_SUCCESS = 'USER_APPROVE_SUCCESS'
export const USER_APPROVE_REQUEST = 'USER_APPROVE_REQUEST'
export const USER_APPROVE_FAIL = 'USER_APPROVE_FAIL'
export const USER_APPROVE_RESET = 'USER_APPROVE_RESET'

export const USER_SUSPEND_SUCCESS = 'USER_SUSPEND_SUCCESS'
export const USER_SUSPEND_REQUEST = 'USER_SUSPEND_REQUEST'
export const USER_SUSPEND_FAIL = 'USER_SUSPEND_FAIL'
export const USER_SUSPEND_RESET = 'USER_SUSPEND_RESET'

export const SELLER_APPLY_REQUEST = 'SELLER_APPLY_REQUEST'
export const SELLER_APPLY_SUCCESS = 'SELLER_APPLY_SUCCESS'
export const SELLER_APPLY_FAIL = 'SELLER_APPLY_FAIL'
export const SELLER_APPLY_RESET = 'SELLER_APPLY_RESET'
