export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';
export const ADD_ADDRESS_RESET = 'ADD_ADDRESS_RESET';

export const FETCH_ADDRESS_REQUEST = 'FETCH_ADDRESS_REQUEST';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAIL = 'FETCH_ADDRESS_FAIL';
export const FETCH_ADDRESS_RESET = 'FETCH_ADDRESS_RESET';
