export const PAYEMENT_FETCH_REQUEST = ' PAYEMENT_FETCH_REQUEST';
export const PAYEMENT_FETCH_SUCCESS = 'PAYEMENT_FETCH_SUCCESS';
export const PAYEMENT_FETCH_FAIL = 'PAYEMENT_FETCH_FAIL';
export const PAYEMENT_FETCH_RESET = 'PAYEMENT_FETCH_RESET';

export const DATA_FETCH_REQUEST = ' DATA_FETCH_REQUEST';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_FAIL = 'DATA_FETCH_FAIL';
export const DATA_FETCH_RESET = 'DATA_FETCH_RESET';

export const RATING_FETCH_REQUEST = 'RATING_FETCH_REQUEST';
export const RATING_FETCH_SUCCESS = 'RATING_FETCH_SUCCESS';
export const RATING_FETCH_FAIL = 'RATING_FETCH_FAIL';
export const RATING_FETCH_RESET = 'RATING_FETCH_RESET';


export const MAX_SALE_PRODUCT_FETCH_REQUEST = 'MAX_SALE_PRODUCT_FETCH_REQUEST';
export const MAX_SALE_PRODUCT_FETCH_SUCCESS = 'MAX_SALE_PRODUCT_FETCH_SUCCESS';
export const MAX_SALE_PRODUCT_FETCH_FAIL = 'MAX_SALE_PRODUCT_FETCH_FAIL';
export const MAX_SALE_PRODUCT_FETCH_RESET = 'MAX_SALE_PRODUCT_FETCH_RESET';


export const MONTHWISE_REVENUE_FETCH_REQUEST = 'MONTHWISE_REVENUE_FETCH_REQUEST';
export const MONTHWISE_REVENUE_FETCH_SUCCESS = 'MONTHWISE_REVENUE_FETCH_SUCCESS';
export const MONTHWISE_REVENUE_FETCH_FAIL = 'MONTHWISE_REVENUE_FETCH_FAIL';
export const MONTHWISE_REVENUE_FETCH_RESET = 'MONTHWISE_REVENUE_FETCH_RESET';