export const CART_FETCH_REQUEST = 'CART_FETCH_REQUEST'
export const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS'
export const CART_FETCH_FAIL = 'CART_FETCH_FAIL'
export const CART_FETCH_RESET = 'CART_FETCH_RESET'

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS'
export const CART_ADD_FAIL = 'CART_ADD_FAIL'
export const CART_ADD_RESET = 'CART_ADD_RESET'

export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST'
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS'
export const CART_REMOVE_FAIL = 'CART_REMOVE_FAIL'
export const CART_REMOVE_RESET = 'CART_REMOVE_RESET'

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST'
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS'
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL'
export const CART_UPDATE_RESET = 'CART_UPDATE_RESET'

export const CART_FETCH_REQUEST_AT_LOGIN = 'CART_FETCH_REQUEST_AT_LOGIN'
export const CART_FETCH_SUCCESS_AT_LOGIN = 'CART_FETCH_SUCCESS_AT_LOGIN'
export const CART_FETCH_FAIL_AT_LOGIN = 'CART_FETCH_FAIL_AT_LOGIN'
export const CART_FETCH_RESET_AT_LOGIN = 'CART_FETCH_RESET_AT_LOGIN'

export const CART_CHECKOUT_REQUEST = 'CART_CHECKOUT_REQUEST'
export const CART_CHECKOUT_SUCCESS = 'CART_CHECKOUT_SUCCESS'
export const CART_CHECKOUT_FAIL = 'CART_CHECKOUT_FAIL'
export const CART_CHECKOUT_RESET = 'CART_CHECKOUT_RESET'
