export const MYORDER_FETCH_REQUEST = ' MYORDER_FETCH_REQUEST';
export const MYORDER_FETCH_SUCCESS = ' MYORDER_FETCH_SUCCESS';
export const MYORDER_FETCH_FAIL = ' MYORDER_FETCH_FAIL';
export const MYORDER_FETCH_RESET = ' MYORDER_FETCH_RESET';

export const MYORDER_ADD_REQUEST = ' MYORDER_ADD_REQUEST';
export const MYORDER_ADD_SUCCESS = ' MYORDER_ADD_SUCCESS';
export const MYORDER_ADD_FAIL = ' MYORDER_ADD_FAIL';

export const MYORDER_UPDATE_REQUEST = ' MYORDER_UPDATE_REQUEST';
export const MYORDER_UPDATE_SUCCESS = ' MYORDER_UPDATE_SUCCESS';
export const MYORDER_UPDATE_FAIL = ' MYORDER_UPDATE_FAIL';
export const MYORDER_UPDATE_RESET = ' MYORDER_UPDATE_RESET';

export const MYORDER_DELETE_REQUEST = ' MYORDER_DELETE_REQUEST';
export const MYORDER_DELETE_SUCCESS = ' MYORDER_DELETE_SUCCESS';
export const MYORDER_DELETE_FAIL = ' MYORDER_DELETE_FAIL';
