export const ORDERDETAILS_FETCH_REQUEST = 'ORDERDETAILS_FETCH_REQUEST';
export const ORDERDETAILS_FETCH_SUCCESS = 'ORDERDETAILS_FETCH_SUCCESS';
export const ORDERDETAILS_FETCH_FAIL = 'ORDERDETAILS_FETCH_FAIL';
export const ORDERDETAILS_FETCH_RESET = 'ORDERDETAILS_FETCH_RESET';
