export const PRODUCT_FETCH_REQUEST = ' PRODUCT_FETCH_REQUEST';
export const PRODUCT_FETCH_SUCCESS = ' PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAIL = ' PRODUCT_FETCH_FAIL';
export const PRODUCT_FETCH_RESET = ' PRODUCT_FETCH_RESET';

export const PRODUCT_RATING_FETCH_REQUEST = 'PRODUCT_RATING_FETCH_REQUEST';
export const PRODUCT_RATING_FETCH_SUCCESS = 'PRODUCT_RATING_FETCH_SUCCESS';
export const PRODUCT_RATING_FETCH_FAIL = 'PRODUCT_RATING_FETCH_FAIL';
export const PRODUCT_RATING_FETCH_RESET = 'PRODUCT_RATING_FETCH_RESET';

export const PRODUCT_COMMENT_FETCH_REQUEST = 'PRODUCT_COMMENT_FETCH_REQUEST';
export const PRODUCT_COMMENT_FETCH_SUCCESS = 'PRODUCT_COMMENT_FETCH_SUCCESS';
export const PRODUCT_COMMENT_FETCH_FAIL = 'PRODUCT_COMMENT_FETCH_FAIL';
export const PRODUCT_COMMENT_FETCH_RESET = 'PRODUCT_COMMENT_FETCH_RESET';

export const PRODUCT_POST_REQUEST = 'PRODUCT_POST_REQUEST';
export const PRODUCT_POST_SUCCESS = 'PRODUCT_POST_SUCCESS';
export const PRODUCT_POST_FAIL = 'PRODUCT_POST_FAIL';
export const PRODUCT_POST_RESET = 'PRODUCT_POST_RESET';

export const COMPANY_FETCH_REQUEST = 'COMPANY_FETCH_REQUEST';
export const COMPANY_FETCH_SUCCESS = 'COMPANY_FETCH_SUCCESS';
export const COMPANY_FETCH_FAIL = 'COMPANY_FETCH_FAIL';
export const COMPANY_FETCH_RESET = 'COMPANY_FETCH_RESET';

export const COMPANY_DELETE_REQUEST = 'COMPANY_DELETE_REQUEST';
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
export const COMPANY_DELETE_FAIL = 'COMPANY_DELETE_FAIL';
export const COMPANY_DELETE_RESET = 'COMPANY_DELETE_RESET';

export const COMPANY_UPDATE_REQUEST = 'COMPANY_UPDATE_REQUEST';
export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS';
export const COMPANY_UPDATE_FAIL = 'COMPANY_UPDATE_FAIL';
export const COMPANY_UPDATE_RESET = 'COMPANY_UPDATE_RESET';

export const COMPANY_ADD_REQUEST = 'COMPANY_ADD_REQUEST';
export const COMPANY_ADD_SUCCESS = 'COMPANY_ADD_SUCCESS';
export const COMPANY_ADD_FAIL = 'COMPANY_ADD_FAIL';
export const COMPANY_ADD_RESET = 'COMPANY_ADD_RESET';

export const CATEGORY_FETCH_REQUEST = 'CATEGORY_FETCH_REQUEST';
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL';
export const CATEGORY_FETCH_RESET = 'CATEGORY_FETCH_RESET';

export const CATEGORY_ADD_REQUEST = 'CATEGORY_ADD_REQUEST';
export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS';
export const CATEGORY_ADD_FAIL = 'CATEGORY_ADD_FAIL';
export const CATEGORY_ADD_RESET = 'CATEGORY_ADD_RESET';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';
export const CATEGORY_DELETE_RESET = 'CATEGORY_DELETE_RESET';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';
