export const SEARCH_PRODUCT_FETCH_REQUEST = ' SEARCH_PRODUCT_FETCH_REQUEST';
export const SEARCH_PRODUCT_FETCH_SUCCESS = ' SEARCH_PRODUCT_FETCH_SUCCESS';
export const SEARCH_PRODUCT_FETCH_FAIL = ' SEARCH_PRODUCT_FETCH_FAIL';
export const SEARCH_PRODUCT_FETCH_RESET = ' SEARCH_PRODUCT_FETCH_RESET';
