export const SELLER_APPLY_REQUEST = 'SELLER_APPLY_REQUEST'
export const SELLER_APPLY_SUCCESS = 'SELLER_APPLY_SUCCESS'
export const SELLER_APPLY_FAIL = 'SELLER_APPLY_FAIL'
export const SELLER_APPLY_RESET = 'SELLER_APPLY_RESET'

export const SELLER_MAX_SELLING_PROD_REQUEST = 'SELLER_MAX_SELLING_PROD_REQUEST'
export const SELLER_MAX_SELLING_PROD_SUCCESS = 'SELLER_MAX_SELLING_PROD_SUCCESS'
export const SELLER_MAX_SELLING_PROD_FAIL = 'SELLER_MAX_SELLING_PROD_FAIL'
export const SELLER_MAX_SELLING_PROD_RESET = 'SELLER_MAX_SELLING_PROD_RESET'

export const SELLER_TOTAL_REVENUE_REQUEST = 'SELLER_TOTAL_REVENUE_REQUEST'
export const SELLER_TOTAL_REVENUE_SUCCESS = 'SELLER_TOTAL_REVENUE_SUCCESS'
export const SELLER_TOTAL_REVENUE_FAIL = 'SELLER_TOTAL_REVENUE_FAIL'
export const SELLER_TOTAL_REVENUE_RESET = 'SELLER_TOTAL_REVENUE_RESET'

export const SELLER_CUST_RATING_REQUEST = 'SELLER_CUST_RATING_REQUEST'
export const SELLER_CUST_RATING_SUCCESS = 'SELLER_CUST_RATING_SUCCESS'
export const SELLER_CUST_RATING_FAIL = 'SELLER_CUST_RATING_FAIL'
export const SELLER_CUST_RATING_RESET = 'SELLER_CUST_RATING_RESET'

export const SELLER_MONTHLY_REVENUE_REQUEST = 'SELLER_MONTHLY_REVENUE_REQUEST'
export const SELLER_MONTHLY_REVENUE_SUCCESS = 'SELLER_MONTHLY_REVENUE_SUCCESS'
export const SELLER_MONTHLY_REVENUE_FAIL = 'SELLER_MONTHLY_REVENUE_FAIL'
export const SELLER_MONTHLY_REVENUE_RESET = 'SELLER_MONTHLY_REVENUE_RESET'

export const SELLER_ALL_CUSTOMER_MYORDERS_REQUEST = 'SELLER_ALL_CUSTOMER_MYORDERS_REQUEST'
export const SELLER_ALL_CUSTOMER_MYORDERS_SUCCESS = 'SELLER_ALL_CUSTOMER_MYORDERS_SUCCESS'
export const SELLER_ALL_CUSTOMER_MYORDERS_FAIL = 'SELLER_ALL_CUSTOMER_MYORDERS_FAIL'
export const SELLER_ALL_CUSTOMER_MYORDERS_RESET = 'SELLER_ALL_CUSTOMER_MYORDERS_RESET'
